apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\kirsta\Downloads\kompose-windows-amd64 (1).exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: eventstore
  name: eventstore
spec:
  ports:
  - name: "1113"
    port: 1113
    targetPort: 1113
  - name: "2113"
    port: 2113
    targetPort: 2113
  selector:
    io.kompose.service: eventstore
status:
  loadBalancer: {}
