apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\kirsta\Downloads\kompose-windows-amd64 (1).exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: eventstore
  name: eventstore
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: eventstore
    spec:
      containers:
      - image: eventstore/eventstore:latest
        name: eventstore
        ports:
        - containerPort: 1113
        - containerPort: 2113
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/eventstore
          name: data.eventstore
      hostname: eventstore
      restartPolicy: Always
      volumes:
      - name: data.eventstore
        persistentVolumeClaim:
          claimName: data.eventstore
status: {}
