apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\kirsta\Downloads\kompose-windows-amd64 (1).exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: 01031990Pc
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /etc/mongo
          name: data.mongodb
      hostname: mongodb
      restartPolicy: Always
      volumes:
      - name: data.mongodb
        persistentVolumeClaim:
          claimName: data.mongodb
status: {}
